server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.181.129:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Jinyuqi-0713
  redis:
      host: 192.168.181.129
  zipkin:
      base-url: http://localhost:9411
      discovery-client-enabled: false
      sender:
        type: web
  sleuth:
      sampler:
        probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true